title: Jennifer Grant 
logo: "/images/IMG_1961.jpeg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a 2020 UC Berkeley graduate, holding a BA in Applied Mathematics.  
  <br><br>
  I found my passion for data science at Berkeley. I love building & improving machine learning models, and 
  communicating insights from data exploration with cool visualizations. 
  <br><br>
  To keep up with the ever-evolving field of data science, I continuously seek out opportunities to learn. 
  Currently enrolled in two ceritified-track edX classes: [Algorithmic Design](https://www.edx.org/course/algorithmic-design-and-techniques) & 
  [Data Structures](https://www.edx.org/course/data-structures-fundamentals). These are classes that I could not fit into my academic schedule
  and believe they will fill technical gaps.
  <br><br>
  <a href="https://www.linkedin.com/in/jenniferlgrant/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-178180468-1 # your Google Analytics tracking ID here
